// examples/react/src/App.jsx
import { useEffect, useState } from "react";
import { Routes, Route, NavLink, useLocation } from "react-router-dom";

import Home from "./pages/Home.jsx";
import Products from "./pages/Products.jsx";
import Checkout from "./pages/Checkout.jsx";

import { useQsiRoute } from "./qsi/useQsiRoute.js";
import { useQsiLoaded } from "./qsi/useQsiLoaded.js";
import { useDocumentTitle } from "./useDocumentTitle.js";
import { enableQsiDebug, disableQsiDebug } from "./qsi/enableQsiDebug.js";

export default function App() {
  const { pathname, search } = useLocation();

  const [debug, setDebug] = useState(false);

  // Turns debug off when you navigate, so the window doesn't reopen on every
  // page. Sits above useQsiRoute on purpose: effects run in the order they're
  // declared, and this has to happen before the re-run calls load().
  useEffect(() => {
    disableQsiDebug();
    setDebug(false);
  }, [pathname, search]);

  // The whole Qualtrics integration. The count is only for the footer.
  const runs = useQsiRoute();

  // Both of these are for the demo, not the integration.
  const loaded = useQsiLoaded();
  useDocumentTitle();

  return (
    <>
      <header>
        <span className="brand">
          <img src="/qualtrics-logo.svg" alt="Qualtrics" />
          <span>SPA demo · React</span>
        </span>
        <nav>
          <NavLink to="/" end>
            Home
          </NavLink>
          <NavLink to="/products">Products</NavLink>
          <NavLink to="/checkout">Checkout</NavLink>
        </nav>
      </header>

      <main>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/products" element={<Products />} />
          <Route path="/checkout" element={<Checkout />} />
        </Routes>
      </main>

      <footer>
        <code>{pathname + search}</code> · 0 page reloads · {runs} re-{runs === 1 ? "run" : "runs"} ·
        deployment code{" "}
        <span className={loaded ? "ok" : "missing"}>{loaded ? "loaded" : "not detected"}</span>
        {loaded && " · "}
        {loaded &&
          (debug ? (
            <span className="ok">debug on</span>
          ) : (
            <button onClick={() => setDebug(enableQsiDebug())}>open debug window</button>
          ))}
      </footer>
    </>
  );
}

// examples/vue/src/App.vue
<script setup>
import { ref, watch } from "vue";
import { RouterLink, RouterView, useRoute } from "vue-router";

import { useQsiRoute } from "./qsi/useQsiRoute.js";
import { useQsiLoaded } from "./qsi/useQsiLoaded.js";
import { enableQsiDebug, disableQsiDebug } from "./qsi/enableQsiDebug.js";

const route = useRoute();

// The whole Qualtrics integration. The count is only for the footer.
const runs = useQsiRoute();

// For the demo, not the integration.
const loaded = useQsiLoaded();

const debug = ref(false);

// Turns debug off when you navigate, so the window doesn't reopen on every
// page. This watcher uses the default flush, so it runs before the
// integration's, which uses flush: "post".
watch(
  () => route.fullPath,
  () => {
    disableQsiDebug();
    debug.value = false;
  }
);
</script>

<template>
  <header>
    <span class="brand">
      <img src="/qualtrics-logo.svg" alt="Qualtrics" />
      <span>SPA demo · Vue</span>
    </span>
    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/products">Products</RouterLink>
      <RouterLink to="/checkout">Checkout</RouterLink>
    </nav>
  </header>

  <main>
    <RouterView />
  </main>

  <footer>
    <code>{{ route.fullPath }}</code> · 0 page reloads · {{ runs }}
    re-{{ runs === 1 ? "run" : "runs" }} · deployment code
    <span :class="loaded ? 'ok' : 'missing'">{{ loaded ? "loaded" : "not detected" }}</span>
    <template v-if="loaded">
      ·
      <span v-if="debug" class="ok">debug on</span>
      <button v-else @click="debug = enableQsiDebug()">open debug window</button>
    </template>
  </footer>
</template>
