// examples/angular/src/app/pages/checkout.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-checkout',
  template: `
    @if (done()) {
      <h1>Done</h1>
      <p>Nothing was sent anywhere.</p>
    } @else {
      <h1>Checkout</h1>
      <form (submit)="place($event)">
        <label>
          Email
          <input type="email" required autocomplete="off" />
        </label>
        <button type="submit">Place order</button>
      </form>
    }
  `,
})
export class Checkout {
  protected done = signal(false);

  protected place(event: Event): void {
    event.preventDefault();
    this.done.set(true);
  }
}

// examples/react/src/pages/Checkout.jsx
import { useState } from "react";

export default function Checkout() {
  const [done, setDone] = useState(false);

  if (done)
    return (
      <>
        <h1>Done</h1>
        <p>Nothing was sent anywhere.</p>
      </>
    );

  return (
    <>
      <h1>Checkout</h1>
      <form
        onSubmit={e => {
          e.preventDefault();
          setDone(true);
        }}
      >
        <label>
          Email
          <input type="email" required autoComplete="off" />
        </label>
        <button type="submit">Place order</button>
      </form>
    </>
  );
}
