// examples/vue/src/pages/Products.vue
<script setup>
import { computed } from "vue";
import { RouterLink, useRoute } from "vue-router";

const items = ["Starter plan", "Standard plan", "Unlimited plan"];

const route = useRoute();
const promo = computed(() => route.query.promo);
</script>

<template>
  <h1>Products</h1>
  <ul class="plans">
    <li v-for="item in items" :key="item">{{ item }}</li>
  </ul>

  <p class="qtip">Point an intercept at this page with "URL contains /products".</p>

  <h2>Query strings count too</h2>
  <p v-if="promo">
    Promo <code>{{ promo }}</code> is on. Same path as before, only the query string changed, and
    the counter still moved. <RouterLink to="/products">Clear it</RouterLink>.
  </p>
  <p v-else>
    <RouterLink to="/products?promo=spring">Add ?promo=spring</RouterLink>. Same path, different
    URL. The composable watches the query string, so it re-runs.
  </p>
</template>

// examples/react/src/pages/Products.jsx
import { Link, useSearchParams } from "react-router-dom";

const items = ["Starter plan", "Standard plan", "Unlimited plan"];

export default function Products() {
  const [params] = useSearchParams();
  const promo = params.get("promo");

  return (
    <>
      <h1>Products</h1>
      <ul className="plans">
        {items.map(item => (
          <li key={item}>{item}</li>
        ))}
      </ul>

      <p className="qtip">Point an intercept at this page with "URL contains /products".</p>

      <h2>Query strings count too</h2>
      {promo ? (
        <p>
          Promo <code>{promo}</code> is on. Same path as before, only the query string changed, and
          the counter still moved. <Link to="/products">Clear it</Link>.
        </p>
      ) : (
        <p>
          <Link to="/products?promo=spring">Add ?promo=spring</Link>. Same path, different URL. The
          hook watches the query string, so it re-runs.
        </p>
      )}
    </>
  );
}
